
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)


export const BaseCursor: typeof import("../app/components/base/BaseCursor.vue")['default']
export const BaseError: typeof import("../app/components/base/BaseError.vue")['default']
export const BaseFooter: typeof import("../app/components/base/BaseFooter.vue")['default']
export const BaseHeader: typeof import("../app/components/base/BaseHeader.vue")['default']
export const BaseIndicator: typeof import("../app/components/base/BaseIndicator.vue")['default']
export const BasePreloader: typeof import("../app/components/base/BasePreloader.vue")['default']
export const ButtonCta: typeof import("../app/components/button/ButtonCta.vue")['default']
export const ButtonIcon: typeof import("../app/components/button/ButtonIcon.vue")['default']
export const ButtonMenu: typeof import("../app/components/button/ButtonMenu.vue")['default']
export const ButtonText: typeof import("../app/components/button/ButtonText.vue")['default']
export const CardMilestone: typeof import("../app/components/card/CardMilestone.vue")['default']
export const CardTeam: typeof import("../app/components/card/CardTeam.vue")['default']
export const CardWhy: typeof import("../app/components/card/CardWhy.vue")['default']
export const CardWhyInvestors: typeof import("../app/components/card/CardWhyInvestors.vue")['default']
export const LayoutGrid: typeof import("../app/components/layout/LayoutGrid.vue")['default']
export const LayoutGridItem: typeof import("../app/components/layout/LayoutGridItem.vue")['default']
export const MediaDynamic: typeof import("../app/components/media/MediaDynamic.vue")['default']
export const MediaImg: typeof import("../app/components/media/MediaImg.vue")['default']
export const MediaVideo: typeof import("../app/components/media/MediaVideo.vue")['default']
export const MotionCarousel: typeof import("../app/components/motion/MotionCarousel.vue")['default']
export const MotionLogoMarquee: typeof import("../app/components/motion/MotionLogoMarquee.vue")['default']
export const MotionSlider: typeof import("../app/components/motion/MotionSlider.vue")['default']
export const PopupCookies: typeof import("../app/components/popup/PopupCookies.vue")['default']
export const SectionCopia de SectionAboutMeetTeamNO: typeof import("../app/components/section/Copia de SectionAboutMeetTeam-NO.vue")['default']
export const SectionCopia de SectionAboutSingleTeam: typeof import("../app/components/section/Copia de SectionAboutSingleTeam.vue")['default']
export const SectionCopia de SectionTeam: typeof import("../app/components/section/Copia de SectionTeam.vue")['default']
export const SectionAboutHero: typeof import("../app/components/section/SectionAboutHero.vue")['default']
export const SectionAboutMeetTeam: typeof import("../app/components/section/SectionAboutMeetTeam.vue")['default']
export const SectionAboutProgramable: typeof import("../app/components/section/SectionAboutProgramable.vue")['default']
export const SectionAboutSingleTeam: typeof import("../app/components/section/SectionAboutSingleTeam.vue")['default']
export const SectionAboutTeam: typeof import("../app/components/section/SectionAboutTeam.vue")['default']
export const SectionAudio: typeof import("../app/components/section/SectionAudio.vue")['default']
export const SectionBlog: typeof import("../app/components/section/SectionBlog.vue")['default']
export const SectionContact: typeof import("../app/components/section/SectionContact.vue")['default']
export const SectionCta: typeof import("../app/components/section/SectionCta.vue")['default']
export const SectionEvents: typeof import("../app/components/section/SectionEvents.vue")['default']
export const SectionGrowth: typeof import("../app/components/section/SectionGrowth.vue")['default']
export const SectionHero: typeof import("../app/components/section/SectionHero.vue")['default']
export const SectionHeroInvestors: typeof import("../app/components/section/SectionHeroInvestors.vue")['default']
export const SectionMilestones: typeof import("../app/components/section/SectionMilestones.vue")['default']
export const SectionMilestonesInvestors: typeof import("../app/components/section/SectionMilestonesInvestors.vue")['default']
export const SectionOverview: typeof import("../app/components/section/SectionOverview.vue")['default']
export const SectionOverviewInvestors: typeof import("../app/components/section/SectionOverviewInvestors.vue")['default']
export const SectionPress: typeof import("../app/components/section/SectionPress.vue")['default']
export const SectionTestimonial: typeof import("../app/components/section/SectionTestimonial.vue")['default']
export const SectionVideo: typeof import("../app/components/section/SectionVideo.vue")['default']
export const SectionWhy: typeof import("../app/components/section/SectionWhy.vue")['default']
export const SectionWhyInvestors: typeof import("../app/components/section/SectionWhyInvestors.vue")['default']
export const SeparationLine: typeof import("../app/components/separation/SeparationLine.vue")['default']
export const Text: typeof import("../app/components/text/Text.vue")['default']
export const TextLogo: typeof import("../app/components/text/TextLogo.vue")['default']
export const TextMarquee: typeof import("../app/components/text/TextMarquee.vue")['default']
export const TextNumber: typeof import("../app/components/text/TextNumber.vue")['default']
export const IconAppstore: typeof import("../app/assets/icon/appstore")['default']
export const IconArrow: typeof import("../app/assets/icon/arrow")['default']
export const IconArrowslide: typeof import("../app/assets/icon/arrowslide")['default']
export const IconChevron: typeof import("../app/assets/icon/chevron")['default']
export const IconCirclecenter: typeof import("../app/assets/icon/circlecenter")['default']
export const IconCircleleft: typeof import("../app/assets/icon/circleleft")['default']
export const IconCircleright: typeof import("../app/assets/icon/circleright")['default']
export const IconClose: typeof import("../app/assets/icon/close")['default']
export const IconGoogleplay: typeof import("../app/assets/icon/googleplay")['default']
export const IconHamburger: typeof import("../app/assets/icon/hamburger")['default']
export const IconLinkedin: typeof import("../app/assets/icon/linkedin")['default']
export const IconLogotext: typeof import("../app/assets/icon/logotext")['default']
export const IconQuote: typeof import("../app/assets/icon/quote")['default']
export const IconTwitter: typeof import("../app/assets/icon/twitter")['default']
export const ScriptAriaLoadingIndicator: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue")['default']
export const ScriptCarbonAds: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']
export const ScriptCrisp: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']
export const ScriptGoogleAdsense: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']
export const ScriptGoogleMaps: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
export const ScriptIntercom: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']
export const ScriptLemonSqueezy: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']
export const ScriptLoadingIndicator: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
export const ScriptStripePricingTable: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
export const ScriptVimeoPlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
export const ScriptYouTubePlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtIcon: typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
export const SymbolInfo: typeof import("../node_modules/nuxt-tradingview/dist/runtime/components/SymbolInfo.vue")['default']
export const TickerTape: typeof import("../node_modules/nuxt-tradingview/dist/runtime/components/TickerTape.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyBaseCursor: LazyComponent<typeof import("../app/components/base/BaseCursor.vue")['default']>
export const LazyBaseError: LazyComponent<typeof import("../app/components/base/BaseError.vue")['default']>
export const LazyBaseFooter: LazyComponent<typeof import("../app/components/base/BaseFooter.vue")['default']>
export const LazyBaseHeader: LazyComponent<typeof import("../app/components/base/BaseHeader.vue")['default']>
export const LazyBaseIndicator: LazyComponent<typeof import("../app/components/base/BaseIndicator.vue")['default']>
export const LazyBasePreloader: LazyComponent<typeof import("../app/components/base/BasePreloader.vue")['default']>
export const LazyButtonCta: LazyComponent<typeof import("../app/components/button/ButtonCta.vue")['default']>
export const LazyButtonIcon: LazyComponent<typeof import("../app/components/button/ButtonIcon.vue")['default']>
export const LazyButtonMenu: LazyComponent<typeof import("../app/components/button/ButtonMenu.vue")['default']>
export const LazyButtonText: LazyComponent<typeof import("../app/components/button/ButtonText.vue")['default']>
export const LazyCardMilestone: LazyComponent<typeof import("../app/components/card/CardMilestone.vue")['default']>
export const LazyCardTeam: LazyComponent<typeof import("../app/components/card/CardTeam.vue")['default']>
export const LazyCardWhy: LazyComponent<typeof import("../app/components/card/CardWhy.vue")['default']>
export const LazyCardWhyInvestors: LazyComponent<typeof import("../app/components/card/CardWhyInvestors.vue")['default']>
export const LazyLayoutGrid: LazyComponent<typeof import("../app/components/layout/LayoutGrid.vue")['default']>
export const LazyLayoutGridItem: LazyComponent<typeof import("../app/components/layout/LayoutGridItem.vue")['default']>
export const LazyMediaDynamic: LazyComponent<typeof import("../app/components/media/MediaDynamic.vue")['default']>
export const LazyMediaImg: LazyComponent<typeof import("../app/components/media/MediaImg.vue")['default']>
export const LazyMediaVideo: LazyComponent<typeof import("../app/components/media/MediaVideo.vue")['default']>
export const LazyMotionCarousel: LazyComponent<typeof import("../app/components/motion/MotionCarousel.vue")['default']>
export const LazyMotionLogoMarquee: LazyComponent<typeof import("../app/components/motion/MotionLogoMarquee.vue")['default']>
export const LazyMotionSlider: LazyComponent<typeof import("../app/components/motion/MotionSlider.vue")['default']>
export const LazyPopupCookies: LazyComponent<typeof import("../app/components/popup/PopupCookies.vue")['default']>
export const LazySectionCopia de SectionAboutMeetTeamNO: LazyComponent<typeof import("../app/components/section/Copia de SectionAboutMeetTeam-NO.vue")['default']>
export const LazySectionCopia de SectionAboutSingleTeam: LazyComponent<typeof import("../app/components/section/Copia de SectionAboutSingleTeam.vue")['default']>
export const LazySectionCopia de SectionTeam: LazyComponent<typeof import("../app/components/section/Copia de SectionTeam.vue")['default']>
export const LazySectionAboutHero: LazyComponent<typeof import("../app/components/section/SectionAboutHero.vue")['default']>
export const LazySectionAboutMeetTeam: LazyComponent<typeof import("../app/components/section/SectionAboutMeetTeam.vue")['default']>
export const LazySectionAboutProgramable: LazyComponent<typeof import("../app/components/section/SectionAboutProgramable.vue")['default']>
export const LazySectionAboutSingleTeam: LazyComponent<typeof import("../app/components/section/SectionAboutSingleTeam.vue")['default']>
export const LazySectionAboutTeam: LazyComponent<typeof import("../app/components/section/SectionAboutTeam.vue")['default']>
export const LazySectionAudio: LazyComponent<typeof import("../app/components/section/SectionAudio.vue")['default']>
export const LazySectionBlog: LazyComponent<typeof import("../app/components/section/SectionBlog.vue")['default']>
export const LazySectionContact: LazyComponent<typeof import("../app/components/section/SectionContact.vue")['default']>
export const LazySectionCta: LazyComponent<typeof import("../app/components/section/SectionCta.vue")['default']>
export const LazySectionEvents: LazyComponent<typeof import("../app/components/section/SectionEvents.vue")['default']>
export const LazySectionGrowth: LazyComponent<typeof import("../app/components/section/SectionGrowth.vue")['default']>
export const LazySectionHero: LazyComponent<typeof import("../app/components/section/SectionHero.vue")['default']>
export const LazySectionHeroInvestors: LazyComponent<typeof import("../app/components/section/SectionHeroInvestors.vue")['default']>
export const LazySectionMilestones: LazyComponent<typeof import("../app/components/section/SectionMilestones.vue")['default']>
export const LazySectionMilestonesInvestors: LazyComponent<typeof import("../app/components/section/SectionMilestonesInvestors.vue")['default']>
export const LazySectionOverview: LazyComponent<typeof import("../app/components/section/SectionOverview.vue")['default']>
export const LazySectionOverviewInvestors: LazyComponent<typeof import("../app/components/section/SectionOverviewInvestors.vue")['default']>
export const LazySectionPress: LazyComponent<typeof import("../app/components/section/SectionPress.vue")['default']>
export const LazySectionTestimonial: LazyComponent<typeof import("../app/components/section/SectionTestimonial.vue")['default']>
export const LazySectionVideo: LazyComponent<typeof import("../app/components/section/SectionVideo.vue")['default']>
export const LazySectionWhy: LazyComponent<typeof import("../app/components/section/SectionWhy.vue")['default']>
export const LazySectionWhyInvestors: LazyComponent<typeof import("../app/components/section/SectionWhyInvestors.vue")['default']>
export const LazySeparationLine: LazyComponent<typeof import("../app/components/separation/SeparationLine.vue")['default']>
export const LazyText: LazyComponent<typeof import("../app/components/text/Text.vue")['default']>
export const LazyTextLogo: LazyComponent<typeof import("../app/components/text/TextLogo.vue")['default']>
export const LazyTextMarquee: LazyComponent<typeof import("../app/components/text/TextMarquee.vue")['default']>
export const LazyTextNumber: LazyComponent<typeof import("../app/components/text/TextNumber.vue")['default']>
export const LazyIconAppstore: LazyComponent<typeof import("../app/assets/icon/appstore")['default']>
export const LazyIconArrow: LazyComponent<typeof import("../app/assets/icon/arrow")['default']>
export const LazyIconArrowslide: LazyComponent<typeof import("../app/assets/icon/arrowslide")['default']>
export const LazyIconChevron: LazyComponent<typeof import("../app/assets/icon/chevron")['default']>
export const LazyIconCirclecenter: LazyComponent<typeof import("../app/assets/icon/circlecenter")['default']>
export const LazyIconCircleleft: LazyComponent<typeof import("../app/assets/icon/circleleft")['default']>
export const LazyIconCircleright: LazyComponent<typeof import("../app/assets/icon/circleright")['default']>
export const LazyIconClose: LazyComponent<typeof import("../app/assets/icon/close")['default']>
export const LazyIconGoogleplay: LazyComponent<typeof import("../app/assets/icon/googleplay")['default']>
export const LazyIconHamburger: LazyComponent<typeof import("../app/assets/icon/hamburger")['default']>
export const LazyIconLinkedin: LazyComponent<typeof import("../app/assets/icon/linkedin")['default']>
export const LazyIconLogotext: LazyComponent<typeof import("../app/assets/icon/logotext")['default']>
export const LazyIconQuote: LazyComponent<typeof import("../app/assets/icon/quote")['default']>
export const LazyIconTwitter: LazyComponent<typeof import("../app/assets/icon/twitter")['default']>
export const LazyScriptAriaLoadingIndicator: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue")['default']>
export const LazyScriptCarbonAds: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']>
export const LazyScriptCrisp: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']>
export const LazyScriptGoogleAdsense: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']>
export const LazyScriptGoogleMaps: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']>
export const LazyScriptIntercom: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']>
export const LazyScriptLemonSqueezy: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']>
export const LazyScriptLoadingIndicator: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']>
export const LazyScriptStripePricingTable: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']>
export const LazyScriptVimeoPlayer: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']>
export const LazyScriptYouTubePlayer: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazySchemaOrgDebug: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']>
export const LazySchemaOrgArticle: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']>
export const LazySchemaOrgBreadcrumb: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']>
export const LazySchemaOrgComment: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgComment']>
export const LazySchemaOrgEvent: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']>
export const LazySchemaOrgFoodEstablishment: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']>
export const LazySchemaOrgHowTo: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']>
export const LazySchemaOrgImage: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgImage']>
export const LazySchemaOrgJobPosting: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']>
export const LazySchemaOrgLocalBusiness: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']>
export const LazySchemaOrgOrganization: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']>
export const LazySchemaOrgPerson: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']>
export const LazySchemaOrgProduct: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']>
export const LazySchemaOrgQuestion: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']>
export const LazySchemaOrgRecipe: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']>
export const LazySchemaOrgReview: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgReview']>
export const LazySchemaOrgVideo: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']>
export const LazySchemaOrgWebPage: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']>
export const LazySchemaOrgWebSite: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']>
export const LazySchemaOrgMovie: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']>
export const LazySchemaOrgCourse: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']>
export const LazySchemaOrgItemList: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']>
export const LazySchemaOrgBook: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgBook']>
export const LazySchemaOrgSoftwareApp: LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']>
export const LazyNuxtIcon: LazyComponent<typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']>
export const LazySymbolInfo: LazyComponent<typeof import("../node_modules/nuxt-tradingview/dist/runtime/components/SymbolInfo.vue")['default']>
export const LazyTickerTape: LazyComponent<typeof import("../node_modules/nuxt-tradingview/dist/runtime/components/TickerTape.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
